--관리자 화면입니다
--C:/BIZWORK/MYDB 폴더에 USER4TS 이름으로 TABLESPACE 생성하고
--이름 : USER475 데이터파일 USER4TS.DBF
--크기 500MB 자동증가 100KB

CREATE TABLESPACE user4TS
DATAFILE 'C:/bizwork/myDB/user4TS.dbf'
size 500M AUTOEXTEND ON NEXT 100k;

--USER4를생성
--비밀번호 : 1234, 기본 TABLESPACE : USER4TS로 생성

CREATE USER user4
IDENTIFIED BY 1234
DEFAULT TABLESPACE user4TS;

GRANT DBA TO user4;

